// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDczOJQhVoNY5lLl8k0GhRnMybbGCE26-o',
    appId: '1:870927440124:web:132b1505403e0437285f79',
    messagingSenderId: '870927440124',
    projectId: 'athr-app',
    authDomain: 'athr-app.firebaseapp.com',
    storageBucket: 'athr-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJAH4oUfXHro36D28mUnkhIqPUF23S9rw',
    appId: '1:870927440124:android:10834ec793c1987c285f79',
    messagingSenderId: '870927440124',
    projectId: 'athr-app',
    storageBucket: 'athr-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0jE4B5WBtylnVjYIXjfBq3-e6acCoxeo',
    appId: '1:870927440124:ios:20847a5051b31298285f79',
    messagingSenderId: '870927440124',
    projectId: 'athr-app',
    storageBucket: 'athr-app.appspot.com',
    androidClientId: '870927440124-isfodsan5k8jaqenk910dnqnlaevmfip.apps.googleusercontent.com',
    iosClientId: '870927440124-q7ai1hp61iam7f3okh0pi0u4gh5iqd1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.athrApp',
  );
}
